adds anyhow support
sunshine-protocol/allo-isolate pull request #23
Opened 2022-07-18 20:00 UTC by lattice0

Adds optional support for implementing `IntoDart` for `anyhow`, needed on https://github.com/fzyzcjy/flutter_rust_bridge/issues/533

2022-07-18 22:27 UTC, fzyzcjy commented on src/into_dart.rs
> +        self.to_string().into_dart()
Hmm I am wondering whether this is sufficient or not? By https://docs.rs/anyhow/1.0.58/anyhow/struct.Error.html, seems that the debug format `{:?}` prints out more information?

Or, if we want more structured solutions we can format it by ourselves

2022-07-18 22:29 UTC, fzyzcjy commented
This is blocking downstream library flutter_rust_bridge. May I know when will it be merged? Thanks

/cc @jerel @shekohex (not sure who is maintaining this lib)

2022-07-19 20:39 UTC, shekohex requested changes
Just a few comments, linting and formatting, and it should be ready to be merged.

2022-07-19 20:39 UTC, shekohex commented on Cargo.toml
> +anyhow = {version="1.0.58", optional = true}
```suggestion
anyhow = { version = "1.0.58", optional = true }
```

2022-08-01 16:17 UTC, shekohex commented
any updates on this @lattice0 and @fzyzcjy ?

2022-08-01 23:31 UTC, lattice0 commented
Will we go with a simple string @fzyzcjy?

2022-08-01 23:42 UTC, fzyzcjy commented
@lattice0 As suggested above

> Hmm I am wondering whether this is sufficient or not? By https://docs.rs/anyhow/1.0.58/anyhow/struct.Error.html, seems that the debug format {:?} prints out more information?
Or, if we want more structured solutions we can format it by ourselves

At least maybe use `{:?}` so we have more info

2022-08-03 01:03 UTC, shekohex commented
Try `cargo +nightly format` them push your changes.

2022-08-03 01:05 UTC, lattice0 commented
`cargo +nightly fmt`

changed 6 files, is it ok to push?

2022-08-03 01:05 UTC, shekohex commented
Yup!

2022-08-03 01:08 UTC, shekohex approved these changes

2022-08-03 01:08 UTC, shekohex commented
Thank you, will publish a new version very soon!

2022-08-03 01:09 UTC, merged

2022-08-03 01:14 UTC, shekohex commented
Released in `v0.1.13`.