Provide `prefer-zero-copy` feature
sunshine-protocol/allo-isolate pull request #39
Opened 2023-05-24 12:44 UTC by temeddix

This pull request was inspired by #38

2023-05-24 14:50 UTC, temeddix commented
If there's anything I can do please let me know :)

2023-05-25 07:13 UTC, shekohex requested changes
Looks good! just left a few small comments.

I would also like that if you could mention or add a section in the rustdocs in the `lib.rs` that describe each feature and what is expected when they are enabled.

2023-05-25 07:13 UTC, shekohex commented on Cargo.toml
> +prefer-zero-copy = []
lets just go with `zero-copy` here.
```suggestion
zero-copy = []
```

2023-05-25 07:13 UTC, shekohex commented on src/into_dart.rs
> +            #[cfg(not(feature="prefer-zero-copy"))]
```suggestion
            #[cfg(not(feature="zero-copy"))]
```

2023-05-25 07:13 UTC, shekohex commented on src/into_dart.rs
> +            #[cfg(feature="prefer-zero-copy")]
```suggestion
            #[cfg(feature="zero-copy")]
```

2023-05-25 07:33 UTC, temeddix commented
I'm not sure about what `catch-unwind` is, so please check if my explanation written in `lib.rs` is correct

2023-05-25 07:38 UTC, shekohex approved these changes
LGTM! Thank you.

2023-05-25 07:41 UTC, temeddix commented
No problem!

2023-05-25 07:44 UTC, merged

2023-05-25 08:08 UTC, temeddix commented
I know it's out of my scope, but may I ask you when this will be provided as a new version, possibly `0.1.15`?

2023-05-25 19:51 UTC, shekohex commented
> I know it's out of my scope, but may I ask you when this will be provided as a new version, possibly `0.1.15`?

Very soon. Probably tomorrow morning.