Fixed a bug with `zero-copy` cargo feature
sunshine-protocol/allo-isolate pull request #41
Opened 2023-05-27 14:58 UTC by temeddix

I am sorry to tell that I left out one of the most important changes when I was making the previous #39 PR.

`self` should be passed to `ManuallyDrop` instead of `self.0`, because it doesn't have `ZeroCopyBuffer` wrapper anymore. I apologize for the mistake.

2023-05-27 23:08 UTC, fzyzcjy commented on src/into_dart.rs
> +                    let mut vec = ManuallyDrop::new(self);
I did not check the code in the last PR. By checking it, it seems we are having some copy-paste here (e.g. this dozen of lines vs ZeroCopyBuffer code). Is it possible we extract it out? For example, extract to a separate function? Then, we will not be faced with such errors.

2023-05-27 23:08 UTC, fzyzcjy requested changes
(see above)

2023-05-28 03:59 UTC, temeddix commented
I made a `vec_to_dart_native_external_type_data` to avoid duplication. Also, I added CI tests with cargo features enabled, which uses `cargo fmt` and `clippy`, that also tells you about an error.

2023-05-29 09:05 UTC, shekohex commented
Could we take a moment to think about how would be able to test something like that in our Mocked DartVM `vm.rs`?

@fzyzcjy did you figure out a way to do End to End testing with Memory checks using real Dart VM And Rust?

2023-05-29 10:45 UTC, shekohex commented
> > @fzyzcjy did you figure out a way to do End to End testing with Memory checks using real Dart VM And Rust?
> 
> Check the valgrind section in my ci.yaml. However, I just checked memory leaks, and do not check invalid memory accesses, because Dart seems to violate so many valgrind operations...
> 
> Related: [dart-lang/sdk#47346](https://github.com/dart-lang/sdk/issues/47346)

Fair enough. @temeddix are you open to make a PR that introduce these kind of checks into our code and then we merge it here into your PR? I want to make sure that we do not introduce any other memory bugs because of a new feature we added.

2023-05-29 10:52 UTC, temeddix commented
I'm not familiar with valgrind tests, but I'll try to apply those in a few days :)

2023-05-29 16:09 UTC, temeddix commented
I dug into the valgrind test code of `flutter_rust_bridge` for some time, and unfortunately, it is too complicated for me to make that work here.

In `flutter_rust_bridge`, Github CI calls a justfile command, and that justfile command calls many other justfile commands, some of which call the `.sh` bash commands in the Dart folder, which calls a Python code, which executes valgrind. This logic is not simple enough for me to fully understand properly.

Apart from this 'deep call stack', there's no Dart example like `flutter_rust_bridge` in this repo. There are only Rust files here, which means there many Dart codes for testing the library's features should be added. I'm not sure if I can understand all the features of this library and organize it into a testing Dart file. This complexity deserves a whole new PR :|

In my opinion, we could focus on fixing the bug and adding CI for Rust linting error in this PR.

2023-05-29 16:11 UTC, shekohex commented
Fair enough. Okay I guess I will go an merge this PR.

2023-05-29 16:11 UTC, shekohex approved these changes

2023-05-29 16:11 UTC, merged